- name: single-server loraserver setup
  hosts: all
  roles:
    - base
    - iptables
    - nginx
    - letsencrypt
    - postgresql
    - redis
    - mosquitto
    - mosquitto-auth
    - lora-gateway-bridge
    - loraserver
    - lora-app-server
    - lora-geo-server

